Source/SINBA.Gui/Controllers/DonneesDeBase/GestionMateriel/MaterielController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sinba.Resources;
using Sinba.BusinessModel.ServiceInterface;
using Sinba.Gui.UIModels;
using Sinba.BusinessModel.Entity;
using Sinba.Gui.Security;
using Dev.Tools.Exceptions;
using Dev.Tools.Logger;
using Sinba.BusinessModel.Entity.ViewModels;


namespace Sinba.Gui.Controllers

{
    #region Attributes
    [IHMLog()]
    [IhmExceptionHandler()]
    [RoutePrefix("DonneesDeBase/GestionMateriel/Materiel")]
    [Route("{action=Index}")]
    [ClaimsAuthorize]
    #endregion
    public class MaterielController : DonneesDeBaseGestionMaterielController
    {
        #region Variables
        private IDonneesDeBaseService donnesDeBaseService;
        private string userId;
        //long id;
        //long id;
        #endregion
        public override string ControllerName { get { return SinbaConstants.Controllers.Materiel; } }
        public MaterielController(IDonneesDeBaseService donnesDeBaseService)

        {
            this.donnesDeBaseService = donnesDeBaseService;
            userId = GetUserId();
        }
        #region Materiel
        #region Views
        public ActionResult Index()
        {
            FillViewBag();
            FillAuthorizedActionsViewBag();
            List<Materiel> lst = new List<Materiel>();
            lst = GetMaterielList();
            return SinbaView(ViewNames.Index, GetMaterielList());
        }
        [ClaimsAuthorize(SinbaConstants.Controllers.Materiel, SinbaConstants.Actions.Index)]
        public ActionResult ListPartial()
        {
            FillViewBag();
            FillAuthorizedActionsViewBag();
            return PartialView(ViewNames.ListPartial, GetMaterielList());
        }                 
        #region Add
        [HttpPost, ValidateInput(false)]
        public ActionResult Add(Materiel materiel)
        {
            if (!ModelState.IsValid)
            {
                FillViewBag(true);
                //return SinbaView(ViewNames.EditPartial, materiel);
            }
            var dto = donnesDeBaseService.InsertMateriel(materiel);
            TreatDto(dto);
            return RedirectToAction(SinbaConstants.Actions.Index);
        }

        [Route(SinbaConstants.Routes.EditId)]
        public ActionResult Edit(long id)
        {
            if (id != 0)
            {
                var dto = donnesDeBaseService.GetMateriel(id);
                TreatDto(dto);
                var materiel = dto.Value;
                if (materiel != null)
                {
                    FillViewBag();
                    return SinbaView(ViewNames.MaterielAddModal, materiel);
                }
            }
            return RedirectToAction(SinbaConstants.Actions.Index);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Materiel materiel)
        {
            if (!ModelState.IsValid)
            {
                FillViewBag();
                return SinbaView(ViewNames.EditPartial, materiel);
            }
            var dto = donnesDeBaseService.UpdateMateriel(materiel);
            TreatDto(dto);
            return RedirectToAction(SinbaConstants.Actions.Index);
        }
        #endregion
        #endregion
        #endregion

        #region Autres
        [ClaimsAuthorize(SinbaConstants.Controllers.Materiel, SinbaConstants.Actions.Index)]
        public ActionResult ComposantPartial(Materiel materiel)
        {
            var id = Request.Params;
            ViewData[DbColumns.MaterielId] = materiel.MaterielId;
            FillViewBag();
            FillAuthorizedActionsViewBag();
            return PartialView(ViewNames.ComposantPartial, GetComposerMateriel(materiel.MaterielId));
        }

        [ClaimsAuthorize(SinbaConstants.Controllers.Materiel, SinbaConstants.Actions.Add)]
        public ActionResult AssocierPartial(long materielid, long domaineid)
        {           
            FillViewBag();
            FillAuthorizedActionsViewBag();
            return PartialView(ViewNames.AssocieAddModal);
        }
        [ClaimsAuthorize(SinbaConstants.Controllers.Materiel, SinbaConstants.Actions.Add)]
        public ActionResult AffectationPartial()
        {           
            FillViewBag();
            FillAuthorizedActionsViewBag();
            return PartialView(ViewNames.AffectationModal);
        }


        //[HttpPost, ValidateInput(false)]
        //[ClaimsAuthorize(SinbaConstants.Controllers.Materiel, SinbaConstants.Actions.Add)]
        //public JsonResult LoadAffectation()
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        FillViewBag(true);
        //    }
        //    AffectationPartial();
        //    return Json(true); 
        //}

        [HttpPost, ValidateInput(false)]
        [ClaimsAuthorize(SinbaConstants.Controllers.Materiel, SinbaConstants.Actions.Add)]
        public JsonResult AddCaracteristique(ComposantCaracteristiqueViewModel ComposantCaracteristique)
        {
            if (!ModelState.IsValid)
            {
                FillViewBag(true);
            }
            var test = new ComposerMateriel();
            var dto = donnesDeBaseService.InsertComposerMateriel(ComposantCaracteristique.ToComposerMateriel());
            TreatDto(dto);
            return Json(dto.HasError, JsonRequestBehavior.AllowGet); 
        }

        [HttpPost, AllowAnonymous]
        [ClaimsAuthorize(SinbaConstants.Controllers.Materiel, SinbaConstants.Actions.Edit)]
        public JsonResult AddAssocieMateriel(string associemateriel)
        {
            if (!ModelState.IsValid)
            {
                FillViewBag(true);
            }
            var associe = new AssociematerielViewModel();
            List<AssocierMateriel> associe1 = associe.ToAssocieMateriel(associemateriel).ToList();           
            var dto = donnesDeBaseService.InsertAssocieMateriel(associe1);          
            return Json(true, JsonRequestBehavior.AllowGet); 
        }

        [HttpPost, ValidateInput(false)]
        [ClaimsAuthorize(SinbaConstants.Controllers.Materiel, SinbaConstants.Actions.Edit)]
        public JsonResult EditCaracteristique(ComposantCaracteristiqueViewModel possedercaracteristique)
        {
            if (!ModelState.IsValid)
            {
                FillViewBag(true);
            }
            var dto = donnesDeBaseService.UpdateCaracteristique(possedercaracteristique.ToComposerMateriel());
            return Json(true);
        }

        [HttpPost,AllowAnonymous]
        public ActionResult AssocierMaterielPartial(long materielid,long domaineid)
        {
            List<AssocierMateriel> lst = new List<AssocierMateriel>();
            List<AssociematerielViewModel> list = new List<AssociematerielViewModel>();
            FillViewBag(true);
            FillAuthorizedActionsViewBag();
            lst = GetAssocierMateriel(materielid);
            ViewBag.AssocierMateriel = GetAssocierMaterielList(domaineid);
            foreach (AssocierMateriel item in lst)
            {
                list.Add(item.ToViewModel());
            }
            return PartialView(ViewNames.AssocierMaterielPartial, list);
        }
        #endregion

        #region Delete

        [Route(SinbaConstants.Routes.DeleteId)]
        public ActionResult Delete(long id)
        {
            if (id != 0)
            {
                var dtoDelete = donnesDeBaseService.DeleteMateriel(id);
                TreatDto(dtoDelete);
            }
            return RedirectToAction(SinbaConstants.Actions.Index);
        }
        [ClaimsAuthorize(SinbaConstants.Controllers.Materiel, SinbaConstants.Actions.Delete)]
        public ActionResult DeleteComposant(long materielid, long composantid, DateTime dateinsertion)
        {
            if(materielid!=0 && composantid!= 0)
            {
                var dto =donnesDeBaseService.RemoveComposant(materielid, composantid, dateinsertion);
            }
            return RedirectToAction(SinbaConstants.Actions.Index);
        }
        #endregion

        #region Modal screens

        #region Modal views
        [AllowAnonymous]
        public ActionResult MaterielAddModalPartial()
        {
            Materiel materiel = new Materiel() ;
            FillAuthorizedActionsViewBag();
            FillViewBag(true);
            return SinbaView(ViewNames.MaterielAddModal, materiel);
        }
        public ActionResult CaracteristiquesModal()
        {
            PossederCaracteristiques caracteristique = new PossederCaracteristiques() ;
            FillAuthorizedActionsViewBag();
            FillViewBag(true);
            return SinbaView(ViewNames.CaracteristiquesModal, caracteristique);
        }

        
        #endregion

        #region Json
        [AllowAnonymous]
        public JsonResult GetMateriel(long materielid)
        {
            Materiel materiel = new Materiel() ;
            var dto = donnesDeBaseService.GetMateriel(materielid);
            if (!TreatDto(dto) && dto.Value != null)
            {
                materiel = dto.Value;
            }
            return Json(materiel, JsonRequestBehavior.AllowGet);
        }

        
         [AllowAnonymous]
        public JsonResult GetComposeMateriel(long materielid, long composantid,DateTime dateinsertion)
        {
            ComposerMateriel materiel = new ComposerMateriel();
            var dto = donnesDeBaseService.GetComposerMaterielwithdependencies(composantid,materielid, dateinsertion);
            if (!TreatDto(dto) && dto.Value != null)
            {
                materiel = dto.Value;
            }
            ComposantCaracteristiqueViewModel composer = new ComposantCaracteristiqueViewModel(materiel);
            return Json( composer, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #endregion

        #region ViewBag
        private void FillAuthorizedActionsViewBag()

        {

Source/SINBA.Gui/Views/Materiel/Index.cshtml
@model IEnumerable
<script src="@Url.VersionedContent("~/Scripts/gmao/Materiel.js")" type="text/javascript"></script>

@using (Html.BeginForm((bool)ViewBag.AddMode ? SinbaConstants.Actions.Add : SinbaConstants.Actions.Index, SinbaConstants.Controllers.Materiel, FormMethod.Post, new { id = "frmMateriel", @class = CssClasses.EditForm }))
{
    Html.AntiForgeryToken();
    Html.Hidden("linkmateriel", Url.Action(SinbaConstants.Actions.GetMateriel, SinbaConstants.Controllers.Materiel));

    @Html.Partial(ViewNames.MaterielAddModal, new Materiel())
    @Html.Partial(ViewNames.CaracteristiquesModal, new Sinba.BusinessModel.Entity.ViewModels.ComposantCaracteristiqueViewModel())
}
@Html.Partial(ViewNames.AssocieAddModal, new List<Sinba.BusinessModel.Entity.ViewModels.AssociematerielViewModel>())
@Html.Partial(ViewNames.AffectationModal, new LocaliserMateriel())
@Html.Partial(ViewNames.ListPartial, Model)
@Html.Hidden("linkcaracteristique", Url.Action(SinbaConstants.Actions.GetCaracteristique, SinbaConstants.Controllers.Materiel))

Source/SINBA.Gui/Views/Materiel/_AssocieAddModal.cshtml
@model  List<Sinba.BusinessModel.Entity.ViewModels.AssociematerielViewModel>
@{
    Html.EnableClientValidation(false);
}

@Html.DevExpress().PopupControl(
    settings =>
    {

        settings.Name = "AssocieModal";
        settings.Width = 600;
        settings.AllowDragging = true;
        settings.CloseAction = CloseAction.CloseButton;
        settings.CloseOnEscape = true;
        settings.PopupAnimationType = AnimationType.None;
        settings.HeaderText = "Matériels Associés";
        settings.Modal = true;
        settings.CallbackRouteValues = new { Controller = SinbaConstants.Controllers.Materiel, Action = SinbaConstants.Actions.AssocierMaterielPartial, MaterielId = (ViewData[DbColumns.MaterielId] ?? "").ToString() };
        settings.AutoUpdatePosition = true;
        settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
        settings.SetContent(() =>
        {
            Html.RenderPartial(ViewNames.AssocierMaterielPartial, new List<Sinba.BusinessModel.Entity.ViewModels.AssociematerielViewModel>());
            Html.DevExpress().Button(
                buttonSettings =>
                {
                    buttonSettings.Name = "btnok";
                    buttonSettings.ControlStyle.CssClass = "button";
                    buttonSettings.Width = 80;
                    buttonSettings.Text = "OK";
                    buttonSettings.ClientSideEvents.Click = "function(s, e){ SaveAssocierMateriel(s,e); } ";
                }
            ).Render();
            Html.DevExpress().Button(
                buttonSettings =>
                {
                    buttonSettings.Name = "btnAnnuler";
                    buttonSettings.ControlStyle.CssClass = "button";
                    buttonSettings.Width = 80;
                    buttonSettings.Text = "Fermer";
                    buttonSettings.ClientSideEvents.Click = "function(s, e){ AssocieModal.Hide(); }";
                }
            ).Render();


        });
    }).GetHtml()

Source/SINBA.Gui/Views/Materiel/_Edit.cshtml
@model Materiel
@{
    Html.EnableClientValidation(false);
}
@Html.DevExpress().PopupControl(
    settings =>
    {
        settings.Name = "MaterielModal";
        settings.Width = 1000;
        settings.AllowDragging = true;
        settings.CloseAction = CloseAction.CloseButton;
        settings.CloseOnEscape = true;
        settings.PopupAnimationType = AnimationType.None;
        settings.HeaderText = "Matériel";
        settings.Modal = true;
        settings.AutoUpdatePosition = true;
        settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.LoadContentViaCallback = LoadContentViaCallback.OnFirstShow;

        settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
        settings.SetContent(() =>
        {
            using (Html.BeginForm("Add", "Materiel", FormMethod.Post, new { id = "Materiel", @class = "edit_form" })){
                Html.Hidden("ProductID");

                @Html.DevExpress().FormLayout(setting => {
                    setting.Name = "ModalModeFormLayout";
                    setting.RequiredMarkDisplayMode = RequiredMarkMode.None;
                    setting.Width = Unit.Percentage(100);
                    setting.Height = Unit.Percentage(100);
                    setting.ColumnCount = 4;

                    setting.NestedExtensionWidth = Unit.Percentage(100);



                    //Code
                    //     if (ViewBag.AddMode == true)
                    //  {
                    //setting.Items.Add(m => m.MaterielId, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox,

                    //maxLength: SinbaConstants.NumericValues.Length.LibelleMax));
                    setting.Items.Add(m => m.MaterielId, label =>
                    {
                        ViewHelper.FormLayoutLabelSettings(label);
                    });
                    // }

                    //Numero de série

                    setting.Items.Add(m => m.NumeroSerie, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox,
                        maxLength: SinbaConstants.NumericValues.Length.LibelleMax));

                    //Libelle

                    setting.Items.Add(m => m.LibelleMateriel, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox,
                        maxLength: SinbaConstants.NumericValues.Length.LibelleMax));


                    // Libelle domaine

                    setting.Items.Add(m => m.DomaineId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,

                        valueType: typeof(string),
                        caption: "Domaine",
                        valueField: "DomaineId",
                        textField: "DomaineId",
                        displayColumns: new string[] { "DomaineId", "LibelleDomaine" }
                        , dataSource: ViewBag.Domaine));

                    //Libelle fournisseur


                    setting.Items.Add(m => m.FournisseurId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,

                        valueType: typeof(string),
                        caption: "Fournisseur",
                        valueField: "FournisseurId",
                        textField: "FournisseurId",
                        displayColumns: new string[] { "FournisseurId", "NomFournisseur" }
                        , dataSource: ViewBag.Fournisseur));


                    //Libelle model


                    setting.Items.Add(m => m.NumeroModel, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,

                        valueType: typeof(string),
                        caption: "Model",
                        valueField: "NumeroModel",
                        textField: "NumeroModel",
                        displayColumns: new string[] { "NumeroModel", "LibelleModel" }
                        , dataSource: ViewBag.Model));


                    // dataSource: ViewBag.Model }));

                    // Sous Famille

                    setting.Items.Add(m => m.SousFamilleId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                        valueType: typeof(string),
                        caption: "Sous Famille",
                        valueField: "SousFamilleId",
                        textField: "SousFamilleId",
                        displayColumns: new string[] { "SousFamilleId", "LibelleSousFamille" }
                        , dataSource: ViewBag.SousFamille));


                    //Numero du bon de commande

                    setting.Items.Add(m => m.NumeroBonCommande, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox,
                        maxLength: SinbaConstants.NumericValues.Length.LibelleMax));

                    //Classe materiel

                    setting.Items.Add(m => m.ClasseMaterielId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                        valueType: typeof(string),
                        caption: "Classe du materiel",
                        valueField: "ClasseMaterielId",
                        textField: "ClasseMaterielId",
                        displayColumns: new string[] { "ClasseMaterielId", "LibelleClasse" }
                        , dataSource: ViewBag.Classemateriel));

                    // dataSource: ViewBag.Model }));

                    //Libelle type materiel

                    setting.Items.Add(m => m.TypeMaterielId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                        valueType: typeof(string),
                        caption: "Type du materiel",
                        valueField: "TypeMaterielId",
                        textField: "TypeMaterielId",
                        displayColumns: new string[] { "TypeMaterielId", "LibelleTypeMateriel" }
                        , dataSource: ViewBag.TypeMateriel));


                    //Date D'acquisition

                    setting.Items.Add(m => m.DateAcquisition, textBox => ViewHelper.FormLayoutDateEditSettings(textBox));

                    //Date De mise en service

                    setting.Items.Add(m => m.DateMiseEnService, textBox => ViewHelper.FormLayoutDateEditSettings(textBox));

                    //Date De sortie

                    setting.Items.Add(m => m.DateSortie, textBox => ViewHelper.FormLayoutDateEditSettings(textBox));

                    //Prix d'achat

                    setting.Items.Add(m => m.PrixAchat, textBox => ViewHelper.FormLayoutNumericTextBoxSettings(textBox,
                        maxLength: SinbaConstants.NumericValues.Length.LibelleMax));



                    //Groupe inventaire

                    setting.Items.Add(m => m.GroupeInventaireId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                        valueType: typeof(string),
                        caption: "GroupeInventaire",
                        valueField: "GroupeInventaireId",
                        textField: "GroupeInventaireId",
                        displayColumns: new string[] { "GroupeInventaireId", "LibelleGroupeInventaire" }
                        , dataSource: ViewBag.GroupeInventaire));


                    // Observation

                    setting.Items.Add(m => m.Note, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox,
                        maxLength: 200));

                    // Boutons Enregistrer/Annuler

                    setting.Items.Add(i => {
                        i.ShowCaption = DefaultBoolean.False;
                        i.SetNestedContent(() => {
                            Html.DevExpress().Button(
                                buttonSettings => {
                                    buttonSettings.Name = "btnUpdate";
                                    buttonSettings.ControlStyle.CssClass = "button";
                                    buttonSettings.Width = 80;
                                    buttonSettings.Text = "OK";
                                    buttonSettings.UseSubmitBehavior = true;


                                }
                            ).Render();
                            Html.DevExpress().Button(
                                buttonSettings => {
                                    buttonSettings.Name = "btnCancel";
                                    buttonSettings.ControlStyle.CssClass = "button";
                                    buttonSettings.Width = 80;
                                    buttonSettings.Text = "Cancel";
                                    buttonSettings.ClientSideEvents.Click = "function(s, e){ MaterielModal.Hide(); }";
                                }
                            ).Render();
                        });
                    });
                }).Render();
            }
        });

    }).GetHtml()

Source/SINBA.Gui/Views/Materiel/_MaterielAddModal.cshtml
@model Materiel
@{
    Html.EnableClientValidation(false);
}
@Html.DevExpress().PopupControl(settings =>
{
    settings.Name = "MaterielModal";
    settings.Width = 1000;
    settings.AllowDragging = true;
    settings.CloseAction = CloseAction.CloseButton;
    settings.CloseOnEscape = true;
    settings.PopupAnimationType = AnimationType.None;
    settings.HeaderText = "Matériel";
    settings.Modal = true;
    settings.AutoUpdatePosition = true;
    settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
    if (!(ViewBag.AddMode = true))
    {
        settings.LoadContentViaCallback = LoadContentViaCallback.OnFirstShow;
    }
    settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
    settings.SetContent(() =>
    {
        using (ViewBag.AddMode = true ?
         Html.BeginForm("Add", "Materiel", FormMethod.Post, new { id = "Materiel", @class = "edit_form" }) :
         Html.BeginForm("Edit", "Materiel", FormMethod.Post, new { id = "Materiel", @class = "edit_form" }))
        {
            Html.Hidden("MaterielID");
            @Html.DevExpress().FormLayout(setting => {
                setting.Name = "ModalModeFormLayout";
                setting.RequiredMarkDisplayMode = RequiredMarkMode.None;
                setting.Width = Unit.Percentage(100);
                setting.Height = Unit.Percentage(100);
                setting.ColumnCount = 4;
                setting.NestedExtensionWidth = Unit.Percentage(100);

                //setting.Items.Add(m => m.MaterielId, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox, maxLength: SinbaConstants.NumericValues.Length.LibelleMax));

                Html.HiddenFor(m => m.MaterielId);

                //setting.Items.Add(m => m.MaterielId, label =>
                //{
                //    ViewHelper.FormLayoutLabelSettings(label);
                //});

                //Numero de série
                setting.Items.Add(m => m.NumeroSerie, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox,maxLength: SinbaConstants.NumericValues.Length.LibelleMax));

                //Libelle
                setting.Items.Add(m => m.LibelleMateriel, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox,maxLength: SinbaConstants.NumericValues.Length.LibelleMax));

                // Libelle domaine
                setting.Items.Add(m => m.DomaineId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                    valueType: typeof(string),
                    caption: "Domaine",
                    valueField: "DomaineId",
                    textField: "LibelleDomaine",
                    displayColumns: new string[] {"LibelleDomaine"}
                    , dataSource: ViewBag.Domaine));

                //Libelle fournisseur
                setting.Items.Add(m => m.FournisseurId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                    valueType: typeof(string),
                    caption: "Fournisseur",
                    valueField: "FournisseurId",
                    textField: "NomFournisseur",
                    displayColumns: new string[] {"NomFournisseur" }
                    , dataSource: ViewBag.Fournisseur));


                //Libelle model
                setting.Items.Add(m => m.NumeroModel, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                    valueType: typeof(string),
                    caption: "Model",
                    valueField: "NumeroModel",
                    textField: "LibelleModel",
                    displayColumns: new string[] {"LibelleModel" }
                    , dataSource: ViewBag.Model));

                // Sous Famille
                setting.Items.Add(m => m.SousFamilleId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                    valueType: typeof(string),
                    caption: "Sous Famille",
                    valueField: "SousFamilleId",
                    textField: "LibelleSousFamille",
                    displayColumns: new string[] {"LibelleSousFamille" }
                    , dataSource: ViewBag.SousFamille));


                //Numero du bon de commande
                setting.Items.Add(m => m.NumeroBonCommande, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox, maxLength: SinbaConstants.NumericValues.Length.LibelleMax));

                //Classe materiel
                setting.Items.Add(m => m.ClasseMaterielId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                    valueType: typeof(string),
                    caption: "Classe du materiel",
                    valueField: "ClasseMaterielId",
                    textField: "LibelleClasse",
                    displayColumns: new string[] { "LibelleClasse" }
                    , dataSource: ViewBag.Classemateriel));

                //Libelle type materiel
                setting.Items.Add(m => m.TypeMaterielId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                    valueType: typeof(string),
                    caption: "Type du materiel",
                    valueField: "TypeMaterielId",
                    textField: "LibelleTypeMateriel",
                    displayColumns: new string[] { "LibelleTypeMateriel" }
                    , dataSource: ViewBag.TypeMateriel));

                //Date D'acquisition
                setting.Items.Add(m => m.DateAcquisition, textBox => ViewHelper.FormLayoutDateEditSettings(textBox));

                //Date de Dortie
                setting.Items.Add(m => m.DateSortie, textBox => ViewHelper.FormLayoutDateEditSettings(textBox));

                //Date De mise en service
                setting.Items.Add(m => m.DateMiseEnService, textBox => ViewHelper.FormLayoutDateEditSettings(textBox));

                // Actif
                setting.Items.Add(m => m.Actif, checkbox =>ViewHelper.FormLayoutCheckBoxSetting(checkbox));

                //Immobilisé
                setting.Items.Add(m => m.Immobilise, checkbox =>ViewHelper.FormLayoutCheckBoxSetting(checkbox));

                //Prix d'achat
                setting.Items.Add(m => m.PrixAchat, textBox => ViewHelper.FormLayoutNumericTextBoxSettings(textBox, maxLength: SinbaConstants.NumericValues.Length.LibelleMax));

                //Groupe inventaire

                setting.Items.Add(m => m.GroupeInventaireId, comboBox => ViewHelper.FormLayoutComboBoxSettings(comboBox,
                    valueType: typeof(string),
                    caption: "GroupeInventaire",
                    valueField: "GroupeInventaireId",
                    textField: "LibelleGroupeInventaire",
                    displayColumns: new string[] {"LibelleGroupeInventaire"}
                    , dataSource: ViewBag.GroupeInventaire));

                //Garantie
                setting.Items.Add(m => m.Garantie, textBox => ViewHelper.FormLayoutDateEditSettings(textBox));

                // Observation
                setting.Items.Add(m => m.Note, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox,maxLength: 200));

                //Numero d'Immobilisation
                setting.Items.Add(m => m.NumeroImmobilisation, textBox => ViewHelper.FormLayoutTextBoxSettings(textBox,maxLength: 200));

                // Boutons Enregistrer/Annuler
                setting.Items.Add(i => {
                    i.ShowCaption = DefaultBoolean.False;
                    i.SetNestedContent(() => {
                        Html.DevExpress().Button(
                            buttonSettings => {
                                buttonSettings.Name = "btnUpdate";
                                buttonSettings.ControlStyle.CssClass = "button";
                                buttonSettings.Width = 80;
                                buttonSettings.Text = "OK";
                                buttonSettings.ClientSideEvents.Click = "function(s, e){ SaveMateriel(); } ";


                            }
                        ).Render();
                        Html.DevExpress().Button(
                            buttonSettings => {
                                buttonSettings.Name = "btnCancel";
                                buttonSettings.ControlStyle.CssClass = "button";
                                buttonSettings.Width = 80;
                                buttonSettings.Text = "Annuler";
                                buttonSettings.ClientSideEvents.Click = "function(s, e){ MaterielModal.Hide(); }";
                            }
                        ).Render();
                    });
                });
            }).Render();
        }
    });

}).GetHtml()